using System;
namespace _2._5._2_ClassesAndObjects_Part2_Notes
{
    public class Student
    {
        /*the NextStudentId field will keep track of the next student id to 
         * be assigned to the student.*/ 
        private static int NextStudentId = 1;
        public string Name { get; set; }
        private readonly int studentId;
        public int NumberOfCredits { get; set; }
        public double Gpa { get; set; }

        /* third constructor for our Student class that only requires the 
         * student’s name. Theoretically, the StudentId field would (or could) 
         * be generated by the class itself.
         * 
         * 
         * This works because static fields are shared across all objects 
         * created from the Student class, so it functions as a counter of 
         * sorts for the number of Student objects created.


         */

        public Student(string name, int sId, int numOfCredits, double gpa)
        {
            Name = name;
            studentId = sId;
            NumberOfCredits = numOfCredits;
            Gpa = gpa;
        }

        public Student(string name, int sId)
        {
            Name = name;
            studentId = sId;
            NumberOfCredits = 0;
            Gpa = 0.0; 
        }

        public Student(string name)
        {
            Name = name;
            studentId = NextStudentId;
            NextStudentId++;
            NumberOfCredits = 0;
            Gpa = 0.0;
        }

        public string StudentInfo()
        {
            return (Name + " has a GPA of " + Gpa);
        }

        public string getGradeLevel()
        {
            //TODO: retrun the student's grade level based on the # of credits they have.
            //Freshman (0-29 credits), Sophomore (30-59 credits), Junior (60-89 credits), or Senior (90+ credits).
            if (NumberOfCredits > 0 && NumberOfCredits <= 29)
            {
                return "Freshman";
            }
            else if (NumberOfCredits >= 30 && NumberOfCredits <= 59)
            {
                return "Sophmore";
            }
            else if (NumberOfCredits >= 60 && NumberOfCredits <= 89)
            {
                return "Junior";
            }
            else if (NumberOfCredits >= 90) 
            {
                return "Sophmore";
            }
            else
            {
                return "Not Valid or Not a Student.";
            }

        }

        public void AddGrade(int courseCredits, double grade)
        {
            //TODO: Finish in exercise.
            double qualityScore = grade * courseCredits;
            double totalQualityScore =+ qualityScore;
            double numberOfCredits =+ courseCredits;
            double Gpa = totalQualityScore / totalQualityScore;
           
        }


    }
}
